name: Bug Report
description: File a bug about components
title: "Bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: input
    id: react
    attributes:
      label: React and ReactDOM version
      description: What version of React and ReactDOM are you using?
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - All
        - Firefox
        - Chrome
        - Safari
        - Safari Mobile
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you confirm that you read the [documentation](https://design.wonderflow.ai)
      options:
        - label: I've searched across open and closed issues for similiar bug reports
          required: true
  - type: checkboxes
    id: project_assign
    attributes:
      label: Project assignment
      description: You confirm that you assigned this issues to Wanda project. Issues without project assignment will NOT be considered.
      options:
        - label: I've assigned Wanda Design System project from the sidebar on the right.
          required: true          
