export const headingsStyleConfig = {
  height: 50,
  fontFamily: 'system-ui',
  title: {
    height: 23.5,
    fill: 'dark-gray',
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 1.25,
    textAnchor: 'start',
    verticalAnchor: 'start',
    x: 0,
    y: 0,
  },
  subtitle: {
    height: 19,
    fill: 'gray',
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 1,
    textAnchor: 'start',
    verticalAnchor: 'start',
    x: 0,
    y: 25,
  },
};
